
GET http://localhost:3000/users/

###
POST http://localhost:3000/register/
Content-Type: application/json

{
    "username":"jaya12",
    "password":"jaya@2024"
}


###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"jaya1",
    "password":"jaya@2023"
}
